#!/usr/bin/env python
# This script fixes files generated by buggy SolidWorks to URDF Exporter plugin
import os, fnmatch
from subprocess import call

fromstr = \
'''    <limit
      effort="0"
      velocity="0" />'''

tostr  = \
'''    <limit
      lower="-1.5708"
      upper="1.5708"
      effort="1000"
      velocity="0.25" />'''

def multiline_file_replace(filename, fromstr, tostr):
  with open(filename, 'r') as f:
    text = f.read()

  text = text.replace(fromstr, tostr)
  with open(filename, 'w') as f:
    f.write(text)

pth = os.path.dirname(os.path.realpath(__file__))
for filename in os.listdir(pth):
    if fnmatch.fnmatch(filename, '*.URDF') or \
       fnmatch.fnmatch(filename, '*.urdf'):
	call(["fromdos", pth+'/'+filename])
	multiline_file_replace(pth+'/'+filename, fromstr, tostr)
	multiline_file_replace(pth+'/'+filename, '.stl', '.STL')

pth=pth+'/..'
for filename in os.listdir(pth):
    if fnmatch.fnmatch(filename, 'package.xml'):
	call(["fromdos", pth+'/'+filename])
	multiline_file_replace(pth+'/'+filename, 'me2email.com', 'me@mail.com')

pth=pth+'/launch'
for filename in os.listdir(pth):
    if fnmatch.fnmatch(filename, '*.launch'):
	call(["fromdos", pth+'/'+filename])
	multiline_file_replace(pth+'/'+filename, 'robots', 'urdf')


